### ISSUE TITLE
Multiword Expressions in UD v2

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_v2#14]
I'm generally okay with this, but a couple of comments for @mcdm :
- It seems fine for English/French to make `fixed` right-headed, but I'm sure that it's only a matter of time till we find a language where it seems a left-headed analysis would be better. Perhaps even something like Arabic, which is more consistently head-initial?
- I didn't understand the bit at the bottom about `reparandum`. Wasn't `reparandum` always right-headed? So doesn't it just remain unchanged?  (While agreeing that a hard choice is required and a "catastrophe" occurs, you could also analyze that last example as `appos` if that seemed better, so the only problem is the catastrophe....)

**Comment by jnivre** [comment]
Here is my proposal for how to deal with fixed, flat, MWEs and complex predicates (see also issue #20):

1. fixed — this replaces mwe and should be used only for fixed MWEs in the sense of Sag et al. (as before, except that many people misunderstood this)

2. flat — this replaces name and is broadened to include exocentric semi-fixed MWEs, including names and complex numerals (and what else?)

3. compound — this remains essentially the same and contrasts with flat by covering endocentric semi-fixed expressions like noun-noun compounds

One question at this point is whether “compound” should be restricted to semi-fixed MWEs (as suggested by Bill Croft), in which case it should arguable no longer include particle verbs even as a subtype. This brings us to the complex predicates, of which there are at least three types to consider: particle verbs (prt), serial verb constructions (svc), and light-verb constructions (lvc). (By lvc I here mean really grammaticalized cases as in Persian, which are in fact quite similar to particle verbs, not semantically non-compositional but syntactically regular constructions like “take a photo (of)” in English.)

I see four different ways of incorporating these into the above scheme:

1. Treat them all as subtypes of compound (:prt, :svc, :lvc). This would mean that “compound” is not restricted to semi-fixed expressions, but (unlike Bill) I don’t see this as a problem. However, it would also mean that compound is not restricted to endocentric constructions, because as far as I understand svc is exocentric.

2. Keep :prt and and :lvc as subtypes of compound, but remove svc on the grounds that it is not endocentric. This could be done in two ways:

2a. Add a new universal relation svc (Chris’s suggestion).
2b. Treat :svc as a subtype of flat (because it is exocentric).

3. Add a new relation cxp (with or without subtypes :prt, :svc, :lvc) to cover all three cases of complex predicates. This is what Bill suggested, and it would mean that compound could be restricted to semi-fixed MWEs.

My own preference is probably for 1, as a good compromise solution that maximizes backward compatibility. It is possible that 3 is the best solution in the long run, but it seems risky to make such a radical change at the last minute. 2a is okay and consistent with what we are proposing for clf, but I am not quite convinced that svc is so special compared to prt and lvc that only the former deserves a universal relation. 2b strikes me as the worst because it would make flat too heterogeneous.

**Comment by dan-zeman** [comment]
Just adding the reference to Sag et al. (hope this is the one @jnivre refers to):
Ivan A. Sag et al.: [Multiword Expressions: A Pain in the Neck for NLP](http://www.springerlink.com/content/978-3-540-43219-7/#section=653450&page=1&locus=0) (2002) in: LECTURE NOTES IN COMPUTER SCIENCE, Vol. 2276, pp. 1-15.

**Comment by dan-zeman** [comment]
Looks like we have similar preferences :-)
+2 for option 1
+1 for option 3 (although MarkDown refuses to show the number "3" above)
0 for option 2 (but agreed that 2b is worse than 2a)

**Comment by manning** [comment]
`flat`: Would we now include dates (Sept 18, 1965, etc.) among `flat`? There was a long discussion of dates in issue #210 (currently closed), including some arguments for various languages, but maybe really they should just be called `flat`? At any rate, dates are common enough in text that it seems like the v2 guidelines should at least say what to do.

**Comment by manning** [comment]
Serial verbs: I can live with using subtypes of compound for everything at the moment, and I think time is running out for further discussion now. It's workable for the moment, and would be relatively easy to change later.

However, FWIW, my opinions are:

- Ultimately, I think it isn't that satisfactory to lump all these things under `compound` because `compound` loses meaning. Originally, `compound` was meant to be for lexicalized compound formation, like noun compounds, but realizing this can also happen with other POS. While I think it is true that serial verbs are lexicalized to some extent, they are clearly syntactically way more flexible, and in most language take objects, etc. and have commonly been analyzed in phrase structure terms as a sequence of VPs for this reason ("she take basket cover fish" or similar). This is an argument for having something like a separate cxp relation. But to some extent this shows that we should clarify our "compound". We could even rename it. I think to many linguists, "compound" is suggestive of something that is fixed and contiguous, often showing phonological properties of being a compound. We've already moved away from that, since, while in German, verb particles sometimes genuinely compound, in English `compound:prt` arguably never compound, and in all of Germanic they can be non-contiguous, allowing a syntactic flexibility beyond standard "compounds".

 - In particular, there is argumentation from some languages that there are both complex predicates and verb compounds, and they are different. See for example Alexandra Y. Aikhenvald, 1999, Serial Constructions and Verb Compounding Evidence from Tariana (North Arawak), _Studies in Language_ https://benjamins.com/#catalog/journals/sl.23.3.02aik/details – not available online, I think.

- I think that serial verbs aren't fully uniform and that in many cases a flat, exocentric analysis is right, but there are also cases, more akin to English resultatives, where two verbs join together in what is better viewed as a endocentric construction. There are various articles that talk about this and suggest two structures. We may wish to distinguish these two. At the moment, resultatives are endocentric. Here, I'm not in agreement with Bill Croft who puts everything including these and particle verbs into one massive class.

**Comment by jnivre** [comment]
The majority seems to be in favor of option 1 for UD v2.
