### ISSUE TITLE
Provide a dependency for serial verb constructions

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_v2#20]
I'm just putting this here as a placeholder. 

Typologically, this is something that I think we are still missing and which is inadequately covered by our present UD and v2 proposals: 
[Wikipedia](https://en.wikipedia.org/wiki/Serial_verb_construction)
[Haspelmath paper](https://www.eva.mpg.de/fileadmin/content_files/linguistics/conferences/2015-diversity-linguistics/Haspelmath_paper.pdf)

**Comment by jnivre** [comment]
If we decide to generalise "flat" to exocentric multiword expressions, then "flat" or possibly "flat:svc" would be a candidate. Otherwise, "compound" or "compound:svc" would probably be the best option. The latter would then contrast with "compound:lvc", which is used in languages like Persian that has grammaticalised light verb constructions, and "compound:prt", which is used for particle verbs. This would bring all (?) the complex predicates together under the "compound" label and would obviate the need for a "cxp" relation.

**Comment by jnivre** [comment]
We seem to have converged on "compound:svc" as an acceptable temporal solution.
